openapi: 3.0.0
info:
  title: Express API
  version: 1.0.0
servers:
  - url: /api/v1
    description: Base API URL

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
